### ISSUE TITLE
Mobile optimization

### ISSUE THREAD

**Issue by chocolatkey** [cdrx/django-admin-menu#11]
Hi, great menubar. Unfortunately, the bar is not optimized for mobile devices, and in Django 2, which is now nicely optimized for phones and co, the menubar sadly breaks the appearance of the admin panel. There are multiple ways this could be fixed with some CSS. Django 2's "responsive.css" has some rules under `@media (max-width: 1024px)` that start breaking the layout, maybe some CSS could be added to django-admin-menu to adapt to these changes

**Comment by chocolatkey** [comment]
Interesting: you are adding height: 80px to #header. My issue with the bar looks like this:
![image](https://user-images.githubusercontent.com/13407784/39611726-d7633872-4f0e-11e8-88d9-3344818f7a70.png)
But if I remove that rule (fallback to responsive.css height: auto), it already looks better:
![image](https://user-images.githubusercontent.com/13407784/39611752-043c03f6-4f0f-11e8-8141-7e0adbcdc587.png)
but then we still have this:
![image](https://user-images.githubusercontent.com/13407784/39611757-168cfb8c-4f0f-11e8-8277-3527ea3dcdfd.png)
:(

**Comment by cdrx** [comment]
![Uploading Screenshot 2020-04-06 at 17.04.19.png…]()
