### ISSUE TITLE
Contributing to django-admin-interface

### ISSUE THREAD

**Issue by fabiocaccamo** [cdrx/django-admin-menu#16]
Hi @cdrx , 
I'm the developer of `django-admin-interface`: https://github.com/fabiocaccamo/django-admin-interface , I just discovered this package and I found the horizontal menu a very interesting feature.

Could you be interested to add this feature to `django-admin-interface`?

**Comment by cdrx** [comment]
Your project looks good. 

It looks like you already have a solution for a horizontal menu; but incase its useful I've just pushed  Django 3.0 support to this project

**Comment by fabiocaccamo** [comment]
I received a PR that is a good start for the implementation of this feature, but it needs some work to make it look nicely and responsive.

**Comment by adavie1** [comment]
I would welcome the addition of this to django-admin-interface. Plus I like the way the logos are handled here- I'm having issues with admin-interface in that regard.

On the other hand, the popups in admin-interface are great. Glad to see this thread, since I was thinking of merging both projects on my own!

**Comment by fabiocaccamo** [comment]
@adavie1 thanks for your feedback. If you have any problem with `django-admin-interface` just open an issue.

**Comment by cdrx** [comment]
I'm happy for the code in this repo to be copied into `django-admin-interface`, it is open source after all! But I don't think there is any change needed in this GitHub project directly to do that, so I'm going to close this issue. Feel free to reopen if there is anything you need.
