### ISSUE TITLE
Pagination style something is wrong

### ISSUE THREAD

**Issue by tonytony2020** [cdrx/django-admin-menu#18]
It should also custom elements of class `.paginator`.

reproduce steps

custom settings.py with 
```
ADMIN_STYLE = {
    'primary-color': '#2B3746',
    'secondary-color': '#354151',
    'tertiary-color': '#F2F9FC'
}
```

you will see paginator looks like 

![case](https://user-images.githubusercontent.com/63030915/78902586-8f939980-7aac-11ea-8215-7207f81aa28d.png)

**Comment by cdrx** [comment]
Can you upload a picture of what it looks like please?

**Comment by tonytony2020** [comment]
> Can you upload a picture of what it looks like please?

here is 

![78902586-8f939980-7aac-11ea-8215-7207f81aa28d](https://user-images.githubusercontent.com/63030915/80079265-a2b16980-8582-11ea-9089-2ba53f98d4fa.png)

**Comment by cdrx** [comment]
<img width="512" alt="Screenshot 2020-06-27 at 11 15 46" src="https://user-images.githubusercontent.com/11462/85919957-a35aca80-b867-11ea-9bbd-6409ad7d80d7.png">

**Comment by tonytony2020** [comment]
Great!
