### ISSUE TITLE
Resize Image Logo

### ISSUE THREAD

**Issue by aldyahsn** [cdrx/django-admin-menu#2]
Hi, how do I change size of image logo? Because it looks like too small for me. Even though I use higher image resolution it stays on small resolution.

**Comment by cdrx** [comment]
There isn't a setting for this at the moment -- would gladly accept a PR to make it configurable though!

**Comment by cdrx** [comment]
This is now possible via settings.py, by adding:

```ADMIN_STYLE = {
   ....
    'logo-width': 'auto',
    'logo-height': '35px'
}```
