### ISSUE TITLE
seems app_label verbose_name not working to menu

### ISSUE THREAD

**Issue by marlonleite** [cdrx/django-admin-menu#20]
I did check it now and seems not working. 
on templatetag custom_admin_menu.py:
Error here:
`
name = apps.get_app_config(app_label).verbose_name
`
can switch to:
`
name = model._meta.app_config.verbose_name
`
or import apps on try exception
`from django.apps import apps`
`name = apps.get_app_config(app_label).verbose_name`
it will work.

my django version is 3.0.5

**Comment by cdrx** [comment]
Thank you for reporting this, @marlonleite. I've fixed it in `master` and it will be in the next release.
