### ISSUE TITLE
Newbie question: How do I deploy locally?

### ISSUE THREAD

**Issue by adavie1** [cdrx/django-admin-menu#24]
Hi, I'm working on some enhancements to the excellent admin_menu (favicon, sidebar, modals instead of popups) - I 'm kinda new to the Python world (Vue,js, Java, Laravel, etc.). I've already forked this repo.

My question is this this: I want to use the demo app to test my changes. I've got admin-menu installed globally since another project uses it.

**Do I:**

1. copy admin_menu dir into demo?
2. Create a virtualenv? (Still getting my head around that one..)
3. Something else

**Comment by cdrx** [comment]
👋 

For development I use a virtualenv for this project. Inside that env you can run:

```
pip install -e .
```

to install the package in editable mode, and then you should be able to start the demo site by running:

```
cd demo
pip install -r requirements.txt
./manage.py runserver
```

There is a db in the folder with some test data in it. I think the admin login is `admin` with password `password`.

**Comment by cdrx** [comment]
The option of symlinking `admin_menu` inside the `demo` folder might work too 👍 but a virtualenv is probably the better bet if you can make it work.

**Comment by adavie1** [comment]
Thanks for the suggestions- especially the symlink.
