### ISSUE TITLE
setting only can view permissions

### ISSUE THREAD

**Issue by cobia** [cdrx/django-admin-menu#26]
When applying only "Can view" permissions to users and groups, the model does not appear in the menu. However, once we add "Can change" permissions, then it appears in the menu. Can it be configured to show the menu when only "Can view" permission is applied?

**Comment by cdrx** [comment]
There isn't a configuration toggle for this at the moment. It will need some code written to understand the view permission.

**Comment by arturgsb** [comment]
The problem has been fixed in the master branch, but the version has not been created.

**Comment by cdrx** [comment]
Sorry for the wait. This has been released in v1.6 now.
