### ISSUE TITLE
'Library' object has no attribute 'assignment_tag'

### ISSUE THREAD

**Issue by kamilgregorczyk** [cdrx/django-admin-menu#3]
Hi, I wanted to test your lib under django 2.0 with python 3 and apparently in custom_admin_css.py you are using the @register.assignment_tag which is not present. I think a good replacement is `simple_tag`

**Comment by rhoerbe** [comment]
same issue here. Is there any workaround?

**Comment by nmartinezb3** [comment]
This problem is happening to me right now again with django 2.0.4 with the version 1.1 of the django-admin-menu. Any idea?
