### ISSUE TITLE
"Add xxx" button offset

### ISSUE THREAD

**Issue by jurishatov** [cdrx/django-admin-menu#31]
Hello,

Really great project. Thanks for that.
For some reason my "Add xxx" button is misaligned. Don't you know what could be a reason for that?

Django 3.2.8
Checked in Chrome and MS Edge on different machines

![Capture](https://user-images.githubusercontent.com/87261478/138338293-6ac06c0d-b2e1-446b-bdee-c6423a6849d3.PNG)

**Comment by cdrx** [comment]
I don't think this is misaligned; it is just pinned to the right hand side of the screen. If it was aligned with the table, I think it would look odd.
