### ISSUE TITLE
Request new release

### ISSUE THREAD

**Issue by obdulia-losantos** [cdrx/django-admin-menu#34]
Would it be possible to create a new release that contains at least this commit?

https://github.com/cdrx/django-admin-menu/commit/50a87323351de2058f5bd5c53b05839809644ab0

I have a lot of useless and annoying "active1" and "active2" messages in the console... Thanks! :pray:

**Comment by cdrx** [comment]
I've just released v1.6 which includes that commit 👍

**Comment by obdulia-losantos** [comment]
Thanks!
