### ISSUE TITLE
Release 1.2

### ISSUE THREAD

**Issue by cdrx** [cdrx/django-admin-menu#6]
With Django 2.0 support

**Comment by rhoerbe** [comment]
would you mind pushing this to pipit?

**Comment by cdrx** [comment]
Will do — do you know if there are any other incompatibilities with Django 2.0?

**Comment by rhoerbe** [comment]
I tried MENU_WEIGHT, but it did not work for me. Could this be an issue?

**Comment by rhoerbe** [comment]
As my PR seems to be quite specific, I would suggest to push 1.2 to PyPi anyway.
